#!/bin/bash

# ALIASES
alias ls='ls --color --group-directories-first'
alias ll='ls -alF --color --group-directories-first'
alias la='ls -A --color --group-directories-first'
alias l='ls -CF --color --group-directories-first'
alias rm="rm -I"
alias dotgit="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"

function mdtopdf() {
	echo $1;
	pandoc -V geometry:margin=.5in $1.md -o $1.pdf
}

function hugo_server() {
        WSL2_IPADDRESS=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
        hugo server --noHTTPCache --bind $WSL2_IPADDRESS --baseURL=http://$WSL2_IPADDRESS -D -F --gc -w
}

# https://www.tylerquinlivan.com/posts/hugo_on_wsl/

push_my_repos() {
  # Loop through all folders in the current working directory and push changes if they are git repositories
  for folder in */; do
    cd "$folder"
    if [[ -d .git ]]; then
      printf "\n\nChecking the $folder repo "
      git pull origin main
      if [[ $? -ne 0 ]]; then
        printf "\nSkipping the $folder repo (pull failed)"
        continue
      fi
      git commit -a -m "Uploaded by script, no commit msg added"
      if [[ $? -eq 0 ]]; then
        git push origin main
      fi
    fi
    cd ..
  done
}


