#!/bin/bash

# ALIASES
alias ls='ls --color --group-directories-first'
alias ll='ls -alF --color --group-directories-first'
alias la='ls -A --color --group-directories-first'
alias l='ls -CF --color --group-directories-first'
alias rm="rm -I"
alias dotgit="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"

_topdf() {
	echo $1;
	pandoc -V geometry:margin=.5in $1.md -o $1.pdf
}
alias topdf=_topdf

