#!/bin/bash

# ALIASES
alias ls='ls --color --group-directories-first'
alias ll='ls -alF --color --group-directories-first'
alias la='ls -A --color --group-directories-first'
alias l='ls -CF --color --group-directories-first'
alias rm="rm -I"
alias dotgit="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"

function mdtopdf() {
	echo $1;
	pandoc -V geometry:margin=.5in $1.md -o $1.pdf
}

function hugo_server() {
        WSL2_IPADDRESS=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
        hugo server --noHTTPCache --bind $WSL2_IPADDRESS --baseURL=http://$WSL2_IPADDRESS -D -F --gc -w
}

# https://www.tylerquinlivan.com/posts/hugo_on_wsl/


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
function conda_init() {
__conda_setup="$('/home/mario/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/mario/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/mario/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/mario/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
}
